[Interface]
PrivateKey = PRIVKEY
Address = ADDRESS
MTU = 1350
DNS = DNS_SERVERS

[Peer]
PublicKey = SERVER_PUBKEY
PresharedKey = PRESHARED_KEY
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = ENDPOINT
PersistentKeepalive = 25
